spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/reddit-clone
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: reddit.clone.io@gmail.com
    password: tfrdecdidsmysyhc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
    default-encoding: UTF-8
    test-connection: true
logging:
  level:
    sql: debug
jwt:
  token:
    secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
