spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/reddit-clone
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: debug
